title: "revista sinedoque"
description: Revista Sinédoque
url: "https://revistasinedoque.com.br"
baseurl: ""
permalink: /artigos/:title/
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Revista Sinédoque"
